### ISSUE TITLE
[1.0.6] jest 26 not supported anymore

### ISSUE THREAD

**Issue by jlowcs** [danwang/yaml-jest#10]
After bumping to yaml-jest 1.0.6 from 1.0.5, my tests stopped working with the following error:

![image](https://user-images.githubusercontent.com/3777724/143464190-d5949c8e-93da-44ee-b5a9-5f2669ad13a1.png)

**Comment by wmarques** [comment]
Same issue with Jest 27 actually :(

**Comment by theothersideofgod** [comment]
look like this package didn't build well?

**Comment by danwang** [comment]
Should be fixed in 1.1.0 https://www.npmjs.com/package/yaml-jest

**Comment by jlowcs** [comment]
Still not working for me in jest 26, sadly:

![image](https://user-images.githubusercontent.com/3777724/145569731-056f45ba-163b-480f-ac33-74b17dd9f93b.png)

**Comment by danwang** [comment]
@jlowcs fixed in 1.2.0, tested at https://github.com/danwang/yaml-jest/tree/master/examples/jest26
